;this file for FamiTone2 libary generated by text2data tool

combined_music_data:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env26,@env0
	.byte $00
	.byte $70 ;instrument $01
	.word @env2,@env0,@env28
	.byte $00
	.byte $70 ;instrument $02
	.word @env3,@env24,@env0
	.byte $00
	.byte $70 ;instrument $03
	.word @env3,@env25,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env4,@env0,@env0
	.byte $00
	.byte $70 ;instrument $05
	.word @env5,@env24,@env0
	.byte $00
	.byte $70 ;instrument $06
	.word @env5,@env25,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $08
	.word @env7,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $09
	.word @env10,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env5,@env0,@env0
	.byte $00
	.byte $70 ;instrument $0b
	.word @env9,@env0,@env28
	.byte $00
	.byte $30 ;instrument $0c
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $0d
	.word @env2,@env0,@env28
	.byte $00
	.byte $b0 ;instrument $0e
	.word @env9,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0f
	.word @env11,@env26,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env13,@env0,@env28
	.byte $00
	.byte $30 ;instrument $11
	.word @env9,@env0,@env0
	.byte $00
	.byte $70 ;instrument $12
	.word @env14,@env0,@env28
	.byte $00
	.byte $30 ;instrument $13
	.word @env12,@env0,@env0
	.byte $00
	.byte $70 ;instrument $14
	.word @env15,@env0,@env0
	.byte $00
	.byte $30 ;instrument $15
	.word @env16,@env0,@env0
	.byte $00
	.byte $30 ;instrument $16
	.word @env17,@env0,@env0
	.byte $00
	.byte $30 ;instrument $17
	.word @env18,@env0,@env0
	.byte $00
	.byte $30 ;instrument $18
	.word @env19,@env0,@env0
	.byte $00
	.byte $30 ;instrument $19
	.word @env11,@env26,@env0
	.byte $00
	.byte $30 ;instrument $1a
	.word @env20,@env0,@env0
	.byte $00
	.byte $30 ;instrument $1b
	.word @env21,@env0,@env0
	.byte $00
	.byte $70 ;instrument $1c
	.word @env22,@env0,@env30
	.byte $00
	.byte $70 ;instrument $1d
	.word @env23,@env0,@env0
	.byte $00
	.byte $30 ;instrument $1e
	.word @env22,@env0,@env30
	.byte $00
	.byte $30 ;instrument $1f
	.word @env1,@env27,@env30
	.byte $00
	.byte $30 ;instrument $20
	.word @env23,@env0,@env0
	.byte $00

@samples:
	.byte $00+FT_DPCM_PTR,$00,$00	;1
	.byte $00+FT_DPCM_PTR,$00,$00	;2
	.byte $00+FT_DPCM_PTR,$00,$00	;3
	.byte $00+FT_DPCM_PTR,$00,$00	;4
	.byte $00+FT_DPCM_PTR,$00,$00	;5
	.byte $00+FT_DPCM_PTR,$00,$00	;6
	.byte $00+FT_DPCM_PTR,$00,$00	;7
	.byte $00+FT_DPCM_PTR,$00,$00	;8
	.byte $00+FT_DPCM_PTR,$00,$00	;9
	.byte $00+FT_DPCM_PTR,$00,$00	;10
	.byte $00+FT_DPCM_PTR,$00,$00	;11
	.byte $00+FT_DPCM_PTR,$00,$00	;12
	.byte $00+FT_DPCM_PTR,$00,$00	;13
	.byte $00+FT_DPCM_PTR,$00,$00	;14
	.byte $00+FT_DPCM_PTR,$00,$00	;15
	.byte $00+FT_DPCM_PTR,$00,$00	;16
	.byte $00+FT_DPCM_PTR,$00,$00	;17
	.byte $00+FT_DPCM_PTR,$00,$00	;18
	.byte $00+FT_DPCM_PTR,$00,$00	;19
	.byte $00+FT_DPCM_PTR,$00,$00	;20
	.byte $00+FT_DPCM_PTR,$00,$00	;21
	.byte $00+FT_DPCM_PTR,$00,$00	;22
	.byte $00+FT_DPCM_PTR,$00,$00	;23
	.byte $00+FT_DPCM_PTR,$00,$00	;24
	.byte $00+FT_DPCM_PTR,$0c,$0f	;25
	.byte $00+FT_DPCM_PTR,$00,$00	;26
	.byte $04+FT_DPCM_PTR,$1b,$0f	;27
	.byte $00+FT_DPCM_PTR,$00,$00	;28
	.byte $0b+FT_DPCM_PTR,$22,$0f	;29
	.byte $14+FT_DPCM_PTR,$0d,$0f	;30
	.byte $00+FT_DPCM_PTR,$00,$00	;31
	.byte $18+FT_DPCM_PTR,$0a,$0f	;32
	.byte $00+FT_DPCM_PTR,$00,$00	;33
	.byte $00+FT_DPCM_PTR,$00,$00	;34
	.byte $00+FT_DPCM_PTR,$00,$00	;35
	.byte $1b+FT_DPCM_PTR,$36,$0f	;36
	.byte $00+FT_DPCM_PTR,$00,$00	;37
	.byte $00+FT_DPCM_PTR,$00,$00	;38
	.byte $00+FT_DPCM_PTR,$00,$00	;39
	.byte $00+FT_DPCM_PTR,$00,$00	;40
	.byte $00+FT_DPCM_PTR,$00,$00	;41
	.byte $00+FT_DPCM_PTR,$00,$00	;42
	.byte $00+FT_DPCM_PTR,$00,$00	;43
	.byte $00+FT_DPCM_PTR,$00,$00	;44
	.byte $00+FT_DPCM_PTR,$00,$00	;45
	.byte $00+FT_DPCM_PTR,$00,$00	;46
	.byte $00+FT_DPCM_PTR,$00,$00	;47
	.byte $00+FT_DPCM_PTR,$00,$00	;48
	.byte $00+FT_DPCM_PTR,$00,$00	;49
	.byte $00+FT_DPCM_PTR,$00,$00	;50
	.byte $00+FT_DPCM_PTR,$00,$00	;51
	.byte $00+FT_DPCM_PTR,$00,$00	;52
	.byte $00+FT_DPCM_PTR,$00,$00	;53
	.byte $00+FT_DPCM_PTR,$00,$00	;54
	.byte $00+FT_DPCM_PTR,$00,$00	;55
	.byte $00+FT_DPCM_PTR,$00,$00	;56
	.byte $00+FT_DPCM_PTR,$00,$00	;57
	.byte $00+FT_DPCM_PTR,$00,$00	;58
	.byte $00+FT_DPCM_PTR,$00,$00	;59
	.byte $00+FT_DPCM_PTR,$00,$00	;60
	.byte $00+FT_DPCM_PTR,$00,$00	;61
	.byte $00+FT_DPCM_PTR,$00,$00	;62
	.byte $00+FT_DPCM_PTR,$00,$00	;63

@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $c5,$c6,$c7,$05,$c6,$0b,$c5,$0f,$c4,$11,$c3,$14,$c2,$15,$c1,$1d
	.byte $c0,$00,$10
@env3:
	.byte $c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0a
@env4:
	.byte $c8,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$00,$07
@env5:
	.byte $c3,$02,$c2,$02,$c1,$02,$c0,$00,$06
@env6:
	.byte $ca,$c8,$c6,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$03,$c0,$00,$0b
@env7:
	.byte $c6,$c6,$c3,$03,$c2,$03,$c1,$c1,$c0,$00,$08
@env8:
	.byte $c1,$c2,$c3,$03,$c2,$02,$c1,$02,$c0,$00,$08
@env9:
	.byte $c4,$03,$c3,$03,$c2,$30,$c1,$45,$c0,$00,$08
@env10:
	.byte $c8,$c5,$c5,$c4,$c4,$c3,$00,$05
@env11:
	.byte $cf,$cf,$c0,$00,$02
@env12:
	.byte $c4,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0b
@env13:
	.byte $c9,$06,$c8,$08,$c7,$08,$c6,$09,$c5,$0a,$c4,$0e,$c3,$11,$c2,$16
	.byte $c1,$18,$c0,$00,$12
@env14:
	.byte $c5,$03,$c4,$06,$c3,$09,$c2,$23,$c3,$0a,$c4,$11,$c3,$0d,$c2,$0a
	.byte $c1,$0f,$c0,$00,$12
@env15:
	.byte $c2,$03,$c1,$03,$c0,$00,$04
@env16:
	.byte $c8,$03,$c3,$03,$c2,$03,$c1,$0b,$c0,$00,$08
@env17:
	.byte $c9,$c3,$c2,$c1,$c1,$c0,$00,$05
@env18:
	.byte $c9,$c7,$c6,$c5,$c4,$c4,$c3,$02,$c2,$04,$c1,$05,$c0,$00,$0c
@env19:
	.byte $cf,$c0,$00,$01
@env20:
	.byte $c3,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$09
@env21:
	.byte $c2,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$07
@env22:
	.byte $c6,$c7,$02,$c8,$0a,$c7,$07,$c6,$0f,$c5,$13,$c4,$1a,$c3,$27,$c2
	.byte $31,$c1,$4b,$c0,$00,$13
@env23:
	.byte $c5,$c5,$c4,$00,$02
@env24:
	.byte $c0,$c0,$c3,$c3,$c7,$c7,$00,$00
@env25:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$00,$00
@env26:
	.byte $cc,$c0,$00,$01
@env27:
	.byte $cc,$cc,$c0,$00,$02
@env28:
	.byte $c0,$0f,$c1,$c1,$c2,$c2,$c1,$c1,$c0,$c0,$00,$02
@env29:
	.byte $c8,$ca,$cc,$ce,$00,$03
@env30:
	.byte $c0,$0f,$c1,$c2,$c3,$03,$c2,$c1,$c0,$02,$c0,$00,$02


@song0ch0:
@song0ch0loop:
@ref0:
	.byte $84,$41,$41,$41,$8a,$41,$84,$41,$8a,$41,$41,$84,$41,$41,$41,$41
	.byte $8a,$41,$84,$41,$8a,$41,$84,$41,$40,$81
@ref1:
	.byte $86,$47,$47,$47,$8c,$47,$86,$47,$8c,$47,$47,$86,$47,$47,$47,$47
	.byte $8c,$47,$86,$47,$8c,$47,$86,$47,$46,$81
@ref2:
	.byte $39,$39,$39,$8c,$39,$86,$39,$8c,$39,$39,$86,$39,$39,$39,$39,$8c
	.byte $39,$86,$39,$8c,$39,$86,$39,$38,$81
@ref3:
	.byte $3d,$3d,$3d,$8c,$3d,$86,$3d,$8c,$3d,$3d,$86,$3d,$3d,$3d,$3d,$8c
	.byte $3d,$86,$3d,$8c,$3d,$3c,$85
	.byte $ff,$11
	.word @ref0
	.byte $ff,$11
	.word @ref1
	.byte $ff,$11
	.word @ref2
@ref7:
	.byte $3d,$3d,$3d,$8c,$3d,$86,$3d,$8c,$3d,$86,$3d,$3d,$3d,$3d,$8c,$3d
	.byte $3c,$91
@ref8:
	.byte $87,$84,$41,$41,$8a,$40,$85,$84,$41,$8a,$41,$96,$24,$28,$83,$84
	.byte $41,$41,$8a,$41,$96,$2f,$84,$41,$8a,$40,$81
@ref9:
	.byte $96,$2c,$2e,$83,$86,$47,$47,$8c,$47,$96,$2f,$86,$47,$8c,$47,$96
	.byte $2c,$85,$86,$47,$47,$8c,$46,$85,$96,$1e,$85
@ref10:
	.byte $20,$85,$86,$39,$39,$8c,$39,$96,$21,$86,$39,$8c,$38,$89,$86,$39
	.byte $39,$8c,$38,$85,$86,$39,$8c,$38,$81
@ref11:
	.byte $96,$36,$85,$86,$3d,$3d,$8c,$3c,$85,$86,$3d,$8c,$3d,$96,$32,$85
	.byte $86,$3d,$3d,$8c,$3c,$8d
	.byte $ff,$11
	.word @ref8
@ref13:
	.byte $96,$2c,$2e,$83,$86,$47,$47,$8c,$47,$96,$2f,$86,$47,$8c,$47,$96
	.byte $32,$85,$86,$47,$47,$8c,$46,$85,$96,$36,$85
@ref14:
	.byte $38,$85,$86,$39,$39,$8c,$38,$85,$86,$39,$8c,$38,$89,$86,$39,$39
	.byte $8c,$38,$85,$86,$39,$8c,$38,$81
@ref15:
	.byte $96,$3c,$85,$86,$3d,$3d,$8c,$3c,$85,$86,$3d,$8c,$3c,$89,$86,$3d
	.byte $3d,$8c,$3c,$85,$86,$3d,$8c,$3c,$81
@ref16:
	.byte $96,$21,$86,$39,$39,$8c,$39,$86,$39,$8c,$39,$86,$39,$39,$9c,$3d
	.byte $86,$39,$9c,$38,$85,$86,$39,$39,$9c,$36,$85
@ref17:
	.byte $96,$33,$86,$3d,$3d,$9c,$25,$86,$3d,$8c,$3d,$86,$3d,$3d,$8c,$3d
	.byte $86,$3d,$9c,$32,$85,$86,$3d,$3d,$9c,$2c,$85
@ref18:
	.byte $83,$86,$2f,$2f,$9c,$37,$86,$2f,$9c,$37,$86,$2f,$2f,$9c,$37,$86
	.byte $2f,$8c,$2e,$85,$86,$2f,$2f,$9c,$2c,$2e,$83
@ref19:
	.byte $33,$84,$29,$29,$9c,$33,$84,$29,$8a,$29,$84,$29,$29,$9c,$2f,$84
	.byte $29,$9c,$2e,$85,$84,$29,$29,$8a,$28,$85
@ref20:
	.byte $83,$86,$39,$39,$8c,$39,$86,$39,$8c,$39,$86,$39,$38,$85,$39,$9c
	.byte $2c,$85,$86,$39,$39,$9c,$32,$85
@ref21:
	.byte $2c,$2e,$86,$3d,$3d,$9c,$2f,$86,$3d,$8c,$3d,$86,$3d,$3d,$9c,$2d
	.byte $86,$3d,$9c,$2c,$85,$86,$3d,$3d,$8c,$3c,$85
@ref22:
	.byte $83,$86,$2f,$2f,$9c,$3d,$86,$2f,$9c,$3d,$86,$2f,$2f,$8c,$2f,$86
	.byte $2f,$8c,$2e,$85,$86,$2f,$2f,$9c,$46,$85
@ref23:
	.byte $4b,$86,$2f,$2f,$9c,$4b,$86,$2f,$8c,$2f,$86,$2f,$2f,$9c,$46,$8d
	.byte $96,$2c,$2e,$83,$32,$85
@ref24:
	.byte $21,$86,$39,$39,$8c,$39,$86,$39,$8c,$39,$86,$39,$39,$9c,$3d,$86
	.byte $39,$9c,$38,$85,$86,$39,$39,$9c,$36,$85
	.byte $ff,$10
	.word @ref17
	.byte $ff,$11
	.word @ref18
	.byte $ff,$10
	.word @ref19
@ref28:
	.byte $83,$86,$39,$39,$9c,$21,$86,$39,$9c,$25,$86,$39,$39,$8c,$39,$86
	.byte $39,$8c,$38,$85,$86,$39,$38,$9c,$26,$28,$85
@ref29:
	.byte $2d,$86,$3d,$3d,$9c,$29,$86,$3d,$9c,$2d,$86,$3d,$3d,$8c,$3d,$86
	.byte $3d,$8c,$3c,$85,$86,$3d,$3c,$9c,$2c,$2e,$85
@ref30:
	.byte $33,$86,$2f,$2f,$9c,$2f,$86,$2f,$9c,$2f,$86,$2f,$2f,$9c,$2f,$86
	.byte $2f,$8c,$2e,$85,$86,$2f,$2f,$8c,$2e,$85
@ref31:
	.byte $83,$86,$2f,$2f,$8c,$2f,$86,$2f,$8c,$2f,$86,$2f,$2f,$8c,$2e,$9d
	.byte $ff,$11
	.word @ref0
	.byte $ff,$11
	.word @ref1
	.byte $ff,$11
	.word @ref2
	.byte $ff,$10
	.word @ref3
	.byte $ff,$11
	.word @ref0
	.byte $ff,$11
	.word @ref1
	.byte $ff,$11
	.word @ref2
	.byte $ff,$0d
	.word @ref7
@ref40:
	.byte $8f,$9a,$36,$85,$3a,$3c,$8b,$3a,$85,$36,$85,$28,$85
@ref41:
	.byte $9f,$44,$85,$46,$95
@ref42:
	.byte $8f,$36,$85,$3a,$3c,$8b,$3a,$85,$28,$85,$2c,$85
@ref43:
	.byte $8f,$2d,$2f,$2c,$a5
@ref44:
	.byte $8f,$36,$85,$3a,$3c,$8b,$3a,$85,$32,$85,$36,$85
	.byte $ff,$05
	.word @ref41
@ref46:
	.byte $8f,$4e,$85,$4a,$8d,$46,$85,$44,$85,$40,$44,$83
@ref47:
	.byte $8f,$45,$47,$4a,$8d,$46,$85,$44,$8d
@ref48:
	.byte $8f,$a0,$10,$14,$83,$16,$8d,$16,$85,$14,$85,$16,$85
@ref49:
	.byte $9f,$14,$16,$83,$1a,$85,$1e,$8d
@ref50:
	.byte $16,$a5,$10,$14,$83,$16,$85,$14,$85
@ref51:
	.byte $87,$28,$2c,$83,$2e,$85,$2c,$8d,$82,$28,$2c,$83,$2e,$85,$2c,$85
@ref52:
	.byte $8f,$a0,$28,$2c,$83,$2e,$8d,$2c,$85,$28,$85,$2e,$85
@ref53:
	.byte $8f,$82,$2c,$2e,$83,$32,$85,$a0,$2c,$2e,$83,$32,$85,$36,$8d
@ref54:
	.byte $38,$ad,$36,$38,$83,$3c,$85
@ref55:
	.byte $87,$3a,$3c,$87,$3a,$3c,$83,$a2,$3d,$a0,$3c,$9d
	.byte $ff,$10
	.word @ref16
	.byte $ff,$10
	.word @ref17
	.byte $ff,$11
	.word @ref18
	.byte $ff,$10
	.word @ref19
	.byte $ff,$10
	.word @ref20
	.byte $ff,$11
	.word @ref21
	.byte $ff,$10
	.word @ref22
	.byte $ff,$0f
	.word @ref23
	.byte $ff,$10
	.word @ref24
	.byte $ff,$10
	.word @ref17
	.byte $ff,$11
	.word @ref18
	.byte $ff,$10
	.word @ref19
	.byte $ff,$11
	.word @ref28
	.byte $ff,$11
	.word @ref29
	.byte $ff,$10
	.word @ref30
	.byte $ff,$0a
	.word @ref31
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref72:
	.byte $92,$11,$11,$11,$94,$11,$92,$29,$11,$94,$29,$92,$0d,$11,$11,$11
	.byte $94,$11,$92,$29,$2d,$94,$29,$92,$2e,$81
@ref73:
	.byte $94,$2f,$92,$17,$17,$94,$17,$92,$2f,$17,$94,$2f,$92,$11,$17,$17
	.byte $17,$94,$17,$92,$2f,$94,$2f,$92,$2c,$2e,$2c,$81
@ref74:
	.byte $09,$09,$09,$94,$09,$92,$21,$09,$94,$21,$92,$07,$09,$09,$09,$94
	.byte $09,$92,$21,$23,$94,$21,$92,$24,$81
@ref75:
	.byte $94,$25,$92,$0d,$0d,$94,$0d,$92,$25,$0d,$94,$25,$92,$0b,$0d,$94
	.byte $0b,$92,$25,$2d,$2f,$94,$2d,$92,$2c,$2e,$2c,$81
@ref76:
	.byte $11,$11,$11,$94,$11,$92,$29,$11,$94,$29,$92,$0d,$11,$11,$11,$94
	.byte $11,$92,$29,$2d,$94,$29,$92,$2e,$81
	.byte $ff,$12
	.word @ref73
	.byte $ff,$11
	.word @ref74
@ref79:
	.byte $94,$25,$92,$0d,$0d,$94,$0d,$92,$22,$24,$0d,$2c,$2e,$2d,$24,$85
	.byte $94,$24,$85,$92,$0d,$94,$0d,$92,$25,$24,$81
@ref80:
	.byte $11,$94,$10,$91,$82,$24,$28,$83,$2c,$85,$2e,$85,$32,$85,$2c,$2e
	.byte $83
@ref81:
	.byte $97,$2c,$95,$1e,$85,$20,$85
@ref82:
	.byte $af,$36,$38,$83,$36,$85
@ref83:
	.byte $97,$32,$a5
@ref84:
	.byte $97,$24,$28,$83,$2c,$85,$2e,$85,$32,$85,$2c,$2e,$83
@ref85:
	.byte $97,$32,$95,$36,$85,$38,$85
@ref86:
	.byte $af,$36,$38,$83,$3c,$85
@ref87:
	.byte $bf
@ref88:
	.byte $8f,$9a,$38,$9c,$39,$9a,$38,$3d,$38,$91,$36,$85,$32,$85
@ref89:
	.byte $24,$95,$2d,$9c,$2d,$9a,$2e,$32,$83,$2e,$85,$2c,$8d
@ref90:
	.byte $36,$a5,$33,$9c,$33,$9a,$2c,$2e,$83,$32,$85
@ref91:
	.byte $97,$2e,$a5
@ref92:
	.byte $97,$28,$9c,$29,$9a,$28,$2c,$85,$2e,$85,$32,$83,$2c,$2e,$85
@ref93:
	.byte $97,$2c,$a5
@ref94:
	.byte $3c,$a5,$3c,$85,$46,$85,$4a,$85
@ref95:
	.byte $97,$46,$a5
@ref96:
	.byte $8f,$38,$9c,$39,$9a,$38,$3d,$38,$91,$36,$85,$32,$85
	.byte $ff,$0b
	.word @ref89
	.byte $ff,$09
	.word @ref90
@ref99:
	.byte $97,$2e,$a5
@ref100:
	.byte $1e,$20,$87,$24,$89,$29,$9c,$29,$9a,$24,$8b,$26,$28,$85,$2c,$85
@ref101:
	.byte $28,$89,$2c,$89,$2f,$9c,$2f,$9a,$2c,$8b,$2c,$2e,$85,$32,$85
@ref102:
	.byte $2e,$bd
@ref103:
	.byte $a4,$14,$16,$bb
	.byte $ff,$11
	.word @ref72
	.byte $ff,$12
	.word @ref73
	.byte $ff,$11
	.word @ref74
	.byte $ff,$12
	.word @ref75
	.byte $ff,$11
	.word @ref76
	.byte $ff,$12
	.word @ref73
	.byte $ff,$11
	.word @ref74
	.byte $ff,$13
	.word @ref79
@ref112:
	.byte $11,$94,$11,$84,$29,$29,$8a,$28,$85,$84,$29,$8a,$29,$9c,$3a,$3c
	.byte $83,$84,$29,$29,$8a,$29,$9c,$3b,$92,$29,$94,$28,$81
@ref113:
	.byte $92,$11,$94,$11,$84,$29,$29,$8a,$28,$85,$84,$29,$8a,$28,$89,$92
	.byte $11,$94,$11,$92,$29,$94,$29,$92,$2f,$94,$2e,$81
@ref114:
	.byte $92,$17,$94,$17,$86,$2f,$2f,$8c,$2e,$85,$86,$2f,$8c,$2f,$9c,$3a
	.byte $3c,$83,$86,$2f,$2f,$8c,$2f,$9c,$3b,$92,$2f,$94,$2e,$81
@ref115:
	.byte $92,$0d,$94,$0d,$86,$25,$25,$8c,$24,$85,$86,$25,$8c,$25,$9c,$2c
	.byte $85,$92,$0d,$94,$0d,$92,$25,$94,$25,$92,$2b,$94,$2a,$81
@ref116:
	.byte $92,$11,$94,$11,$84,$29,$29,$8a,$28,$85,$84,$29,$8a,$29,$9c,$3a
	.byte $3c,$83,$84,$29,$29,$8a,$29,$9c,$3b,$92,$29,$94,$28,$81
	.byte $ff,$10
	.word @ref113
@ref118:
	.byte $92,$09,$94,$09,$86,$21,$21,$8c,$20,$85,$86,$21,$8c,$21,$9c,$4a
	.byte $85,$86,$21,$21,$8c,$21,$9c,$47,$92,$21,$94,$20,$81
@ref119:
	.byte $92,$0d,$94,$0d,$86,$25,$25,$8c,$24,$85,$86,$25,$8c,$25,$9c,$4a
	.byte $85,$92,$0d,$94,$0d,$92,$25,$94,$25,$92,$2b,$94,$2a,$81
@ref120:
	.byte $83,$84,$29,$29,$8a,$29,$84,$29,$8a,$29,$84,$29,$29,$a2,$17,$84
	.byte $29,$8a,$28,$85,$84,$29,$29,$a2,$14,$85
@ref121:
	.byte $17,$86,$2f,$2f,$a2,$17,$86,$2f,$8c,$2f,$86,$2f,$2f,$8c,$2e,$85
	.byte $86,$2f,$2f,$a2,$1a,$85,$1e,$85
@ref122:
	.byte $83,$86,$21,$21,$a2,$17,$86,$21,$a2,$17,$86,$21,$21,$8c,$21,$86
	.byte $21,$8c,$20,$85,$86,$21,$21,$a2,$16,$85
@ref123:
	.byte $15,$86,$25,$25,$8c,$25,$86,$25,$a2,$15,$86,$25,$25,$a2,$14,$85
	.byte $86,$25,$25,$96,$28,$2c,$83,$2e,$85
@ref124:
	.byte $2d,$84,$29,$29,$8a,$29,$84,$29,$8a,$29,$84,$29,$29,$a2,$2f,$84
	.byte $29,$8a,$28,$85,$84,$29,$29,$a2,$28,$85
@ref125:
	.byte $2f,$86,$2f,$2f,$8c,$2f,$86,$2f,$8c,$2f,$86,$2f,$2f,$96,$32,$85
	.byte $86,$2f,$2f,$a2,$32,$85,$36,$85
@ref126:
	.byte $83,$86,$21,$21,$a2,$39,$86,$21,$a2,$39,$86,$21,$21,$8c,$21,$86
	.byte $21,$8c,$20,$85,$86,$21,$21,$a2,$36,$38,$83
@ref127:
	.byte $3d,$86,$25,$25,$8c,$25,$86,$25,$a2,$3d,$86,$25,$25,$8c,$24,$85
	.byte $a2,$3c,$95
	.byte $ff,$0b
	.word @ref88
	.byte $ff,$0b
	.word @ref89
	.byte $ff,$09
	.word @ref90
@ref131:
	.byte $97,$2e,$a5
	.byte $ff,$0d
	.word @ref92
@ref133:
	.byte $97,$2c,$a5
	.byte $ff,$08
	.word @ref94
@ref135:
	.byte $97,$46,$a5
	.byte $ff,$0b
	.word @ref96
	.byte $ff,$0b
	.word @ref89
	.byte $ff,$09
	.word @ref90
@ref139:
	.byte $97,$2e,$a5
	.byte $ff,$0e
	.word @ref100
	.byte $ff,$0d
	.word @ref101
@ref142:
	.byte $2e,$bd
@ref143:
	.byte $a4,$14,$16,$bb
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref144:
	.byte $80,$28,$00,$28,$00,$29,$01,$41,$29,$01,$24,$00,$28,$00,$28,$00
	.byte $29,$01,$41,$98,$44,$85,$46,$81
@ref145:
	.byte $80,$2e,$00,$2e,$00,$2f,$01,$47,$2f,$01,$28,$00,$2e,$00,$2e,$00
	.byte $2e,$00,$83,$98,$46,$85,$44,$46,$44,$81
@ref146:
	.byte $80,$20,$00,$20,$00,$21,$01,$39,$21,$01,$1e,$00,$20,$00,$20,$00
	.byte $21,$01,$98,$39,$3a,$85,$3c,$81
@ref147:
	.byte $80,$24,$00,$24,$00,$25,$01,$3d,$25,$01,$22,$00,$25,$01,$98,$3d
	.byte $45,$46,$85,$44,$46,$44,$81
	.byte $ff,$16
	.word @ref144
	.byte $ff,$18
	.word @ref145
@ref150:
	.byte $80,$20,$00,$20,$00,$21,$01,$39,$21,$01,$1e,$00,$20,$00,$20,$00
	.byte $21,$01,$39,$98,$3a,$85,$3c,$81
@ref151:
	.byte $80,$24,$00,$24,$00,$25,$01,$98,$3a,$3c,$83,$44,$46,$45,$3c,$89
	.byte $3a,$36,$80,$25,$01,$3c,$00,$3c,$00
@ref152:
	.byte $28,$00,$28,$00,$29,$01,$41,$00,$85,$24,$00,$28,$00,$28,$00,$29
	.byte $01,$41,$41,$29,$00,$81
@ref153:
	.byte $2e,$00,$2e,$00,$2f,$01,$47,$00,$85,$28,$00,$2e,$00,$2e,$00,$2e
	.byte $00,$83,$47,$01,$46,$00,$46,$00
@ref154:
	.byte $20,$00,$20,$00,$21,$01,$39,$00,$85,$20,$00,$20,$00,$20,$00,$21
	.byte $01,$39,$39,$21,$00,$81
@ref155:
	.byte $24,$00,$24,$00,$25,$01,$3d,$00,$85,$22,$00,$24,$00,$24,$00,$24
	.byte $00,$83,$3c,$83,$00,$25,$3c,$81
	.byte $ff,$16
	.word @ref152
	.byte $ff,$18
	.word @ref153
	.byte $ff,$16
	.word @ref154
@ref159:
	.byte $24,$00,$24,$00,$25,$01,$3d,$00,$85,$23,$24,$85,$3d,$3d,$24,$85
	.byte $37,$36,$81
@ref160:
	.byte $20,$83,$00,$20,$00,$20,$83,$00,$20,$00,$39,$01,$20,$83,$00,$20
	.byte $00,$20,$83,$00,$21,$3a,$85
@ref161:
	.byte $24,$83,$00,$24,$00,$24,$83,$00,$24,$00,$3d,$01,$24,$83,$00,$24
	.byte $00,$24,$83,$00,$24,$00,$44,$85
@ref162:
	.byte $2e,$83,$00,$2e,$00,$2e,$83,$00,$2e,$00,$47,$01,$2e,$83,$00,$2e
	.byte $00,$2e,$83,$00,$2f,$2c,$85
@ref163:
	.byte $28,$83,$00,$28,$00,$28,$83,$00,$28,$00,$41,$01,$28,$83,$00,$28
	.byte $00,$28,$83,$00,$41,$3c,$85
	.byte $ff,$17
	.word @ref160
	.byte $ff,$18
	.word @ref161
	.byte $ff,$17
	.word @ref162
@ref167:
	.byte $2e,$83,$00,$2e,$00,$2e,$83,$00,$2e,$00,$47,$01,$2e,$85,$00,$85
	.byte $44,$98,$46,$83,$80,$4a,$85
	.byte $ff,$17
	.word @ref160
	.byte $ff,$18
	.word @ref161
	.byte $ff,$17
	.word @ref162
	.byte $ff,$17
	.word @ref163
	.byte $ff,$17
	.word @ref160
	.byte $ff,$18
	.word @ref161
	.byte $ff,$17
	.word @ref162
@ref175:
	.byte $2e,$83,$00,$2e,$00,$2e,$83,$00,$2e,$00,$47,$01,$2e,$85,$00,$95
@ref176:
	.byte $28,$00,$28,$00,$29,$01,$41,$29,$01,$24,$00,$28,$00,$28,$00,$29
	.byte $01,$41,$98,$44,$85,$46,$81
	.byte $ff,$18
	.word @ref145
	.byte $ff,$16
	.word @ref146
	.byte $ff,$15
	.word @ref147
	.byte $ff,$16
	.word @ref144
	.byte $ff,$18
	.word @ref145
	.byte $ff,$16
	.word @ref150
	.byte $ff,$16
	.word @ref151
@ref184:
	.byte $28,$00,$29,$9e,$41,$40,$89,$40,$8d,$41,$40,$89,$80,$41,$00,$81
@ref185:
	.byte $28,$00,$29,$9e,$41,$40,$89,$40,$8d,$80,$28,$00,$9e,$29,$80,$40
	.byte $00,$9e,$41,$80,$46,$00,$9e,$46,$81
@ref186:
	.byte $80,$2e,$00,$2f,$9e,$47,$46,$89,$46,$8d,$47,$46,$89,$80,$47,$00
	.byte $81
@ref187:
	.byte $24,$00,$25,$9e,$3d,$3c,$89,$3c,$8d,$80,$24,$00,$9e,$25,$80,$3c
	.byte $00,$9e,$3d,$80,$42,$00,$9e,$42,$81
@ref188:
	.byte $80,$28,$00,$29,$9e,$41,$40,$89,$40,$8d,$41,$40,$89,$80,$41,$00
	.byte $81
	.byte $ff,$12
	.word @ref185
@ref190:
	.byte $80,$20,$00,$21,$9e,$39,$38,$89,$38,$8d,$39,$38,$89,$80,$39,$00
	.byte $81
@ref191:
	.byte $24,$00,$25,$9e,$3d,$3c,$89,$3c,$8d,$80,$24,$00,$24,$89,$00,$85
	.byte $ff,$16
	.word @ref152
	.byte $ff,$18
	.word @ref153
	.byte $ff,$16
	.word @ref154
	.byte $ff,$18
	.word @ref155
	.byte $ff,$16
	.word @ref152
	.byte $ff,$18
	.word @ref153
	.byte $ff,$16
	.word @ref154
	.byte $ff,$13
	.word @ref159
	.byte $ff,$17
	.word @ref160
	.byte $ff,$18
	.word @ref161
	.byte $ff,$17
	.word @ref162
	.byte $ff,$17
	.word @ref163
	.byte $ff,$17
	.word @ref160
	.byte $ff,$18
	.word @ref161
	.byte $ff,$17
	.word @ref162
	.byte $ff,$15
	.word @ref167
	.byte $ff,$17
	.word @ref160
	.byte $ff,$18
	.word @ref161
	.byte $ff,$17
	.word @ref162
	.byte $ff,$17
	.word @ref163
	.byte $ff,$17
	.word @ref160
	.byte $ff,$18
	.word @ref161
	.byte $ff,$17
	.word @ref162
	.byte $ff,$10
	.word @ref175
	.byte $fd
	.word @song0ch2loop

@song0ch3:
	.byte $fb,$06
@song0ch3loop:
@ref216:
	.byte $fb,$05,$88,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$90,$1f,$fb,$05
	.byte $8e,$1f,$fb,$03,$88,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05
	.byte $1f,$fb,$03,$1f,$fb,$05,$8e,$1f,$fb,$03,$90,$1f,$fb,$05,$8e,$1f
	.byte $fb,$03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$1e,$81
@ref217:
	.byte $fb,$05,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$90,$1f,$fb,$05,$8e
	.byte $1f,$fb,$03,$88,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f
	.byte $fb,$03,$1f,$fb,$05,$8e,$1f,$fb,$03,$90,$1f,$fb,$05,$8e,$1f,$fb
	.byte $03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$1e,$81
	.byte $ff,$11
	.word @ref217
@ref219:
	.byte $fb,$05,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$90,$1f,$fb,$05,$8e
	.byte $1f,$fb,$03,$88,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f
	.byte $fb,$03,$1f,$fb,$05,$8e,$1f,$fb,$03,$83,$fb,$05,$1f,$fb,$03,$83
	.byte $fb,$05,$1f,$fb,$03,$83
	.byte $ff,$11
	.word @ref216
	.byte $ff,$11
	.word @ref217
	.byte $ff,$11
	.word @ref217
	.byte $ff,$10
	.word @ref219
@ref224:
	.byte $fb,$05,$88,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb
	.byte $05,$90,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb,$05
	.byte $83,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$83,$fb,$05,$90,$1f,$fb
	.byte $03,$83,$fb,$05,$8e,$1f,$fb,$03,$83
@ref225:
	.byte $fb,$05,$88,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb
	.byte $05,$90,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb,$05
	.byte $83,$fb,$03,$1f,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb,$05,$90,$1f
	.byte $fb,$03,$88,$1f,$fb,$05,$8e,$1f,$fb,$03,$88,$1e,$81
@ref226:
	.byte $fb,$05,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb,$05
	.byte $90,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb,$05,$83
	.byte $fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$83,$fb,$05,$90,$1f,$fb,$03
	.byte $83,$fb,$05,$8e,$1f,$fb,$03,$83
	.byte $ff,$11
	.word @ref225
	.byte $ff,$10
	.word @ref226
	.byte $ff,$11
	.word @ref225
	.byte $ff,$10
	.word @ref226
@ref231:
	.byte $fb,$05,$88,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb
	.byte $05,$90,$1f,$fb,$03,$83,$fb,$05,$8e,$1f,$fb,$03,$88,$1f,$fb,$05
	.byte $8e,$1f,$fb,$03,$83,$fb,$05,$88,$1f,$fb,$03,$83,$fb,$05,$1f,$fb
	.byte $03,$83,$fb,$05,$1f,$fb,$03,$83
@ref232:
	.byte $fb,$05,$8e,$1d,$fb,$03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$90,$1f
	.byte $fb,$05,$88,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$8e,$1f,$fb,$05
	.byte $88,$1f,$fb,$03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$90,$1f,$fb,$05
	.byte $88,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$8e,$1e,$81
@ref233:
	.byte $fb,$05,$1d,$fb,$03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$90,$1f,$fb
	.byte $05,$88,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$8e,$1f,$fb,$05,$88
	.byte $1f,$fb,$03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$90,$1f,$fb,$05,$88
	.byte $1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$8e,$1e,$81
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
@ref239:
	.byte $fb,$05,$1d,$fb,$03,$90,$1f,$fb,$05,$88,$1f,$fb,$03,$90,$1f,$fb
	.byte $05,$88,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$8e,$1f,$fb,$05,$90
	.byte $1f,$fb,$03,$83,$fb,$05,$1f,$fb,$03,$83,$fb,$05,$1b,$fb,$03,$83
	.byte $fb,$05,$83,$fb,$03,$83
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$10
	.word @ref239
	.byte $ff,$11
	.word @ref216
	.byte $ff,$11
	.word @ref217
	.byte $ff,$11
	.word @ref217
	.byte $ff,$10
	.word @ref219
	.byte $ff,$11
	.word @ref216
	.byte $ff,$11
	.word @ref217
	.byte $ff,$11
	.word @ref217
	.byte $ff,$10
	.word @ref219
@ref256:
	.byte $fb,$05,$90,$1f,$fb,$03,$83,$fb,$05,$83,$fb,$03,$83,$fb,$05,$1f
	.byte $fb,$03,$83,$fb,$05,$83,$fb,$03,$83,$fb,$05,$1f,$fb,$03,$83,$fb
	.byte $05,$83,$fb,$03,$83,$fb,$05,$1f,$fb,$03,$83,$fb,$05,$83,$fb,$03
	.byte $88,$1e,$81
@ref257:
	.byte $fb,$05,$90,$1f,$fb,$03,$83,$fb,$05,$83,$fb,$03,$83,$fb,$05,$1f
	.byte $fb,$03,$83,$fb,$05,$83,$fb,$03,$83,$fb,$05,$1f,$fb,$03,$83,$fb
	.byte $05,$88,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb,$03,$1f,$fb,$05,$1f,$fb
	.byte $03,$1e,$81
	.byte $ff,$11
	.word @ref256
	.byte $ff,$11
	.word @ref257
	.byte $ff,$11
	.word @ref256
	.byte $ff,$11
	.word @ref257
	.byte $ff,$11
	.word @ref256
	.byte $ff,$11
	.word @ref257
@ref264:
	.byte $fb,$05,$1f,$fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05
	.byte $1f,$fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f,$fb
	.byte $03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f,$fb,$03,$1f
	.byte $fb,$05,$90,$1f,$fb,$03,$8e,$1e,$81
@ref265:
	.byte $fb,$05,$88,$1f,$fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb
	.byte $05,$1f,$fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f
	.byte $fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f,$fb,$03
	.byte $1f,$fb,$05,$90,$1f,$fb,$03,$8e,$1e,$81
	.byte $ff,$11
	.word @ref265
	.byte $ff,$11
	.word @ref265
	.byte $ff,$11
	.word @ref265
	.byte $ff,$11
	.word @ref265
	.byte $ff,$11
	.word @ref265
@ref271:
	.byte $fb,$05,$88,$1f,$fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb
	.byte $05,$1f,$fb,$03,$1f,$fb,$05,$90,$1f,$fb,$03,$88,$1f,$fb,$05,$1f
	.byte $fb,$03,$83,$fb,$05,$83,$fb,$03,$83,$fb,$05,$1f,$fb,$03,$1f,$fb
	.byte $05,$90,$1f,$fb,$03,$8e,$1e,$81
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$10
	.word @ref239
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$11
	.word @ref233
	.byte $ff,$10
	.word @ref239
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref288:
	.byte $32,$85,$32,$85,$3b,$32,$85,$33,$33,$33,$32,$85,$3b,$33,$36,$85
@ref289:
	.byte $32,$85,$32,$85,$3b,$32,$85,$33,$33,$33,$32,$85,$3a,$83,$36,$37
	.byte $36,$81
@ref290:
	.byte $32,$85,$32,$85,$3b,$32,$85,$33,$33,$33,$32,$85,$3b,$33,$36,$83
	.byte $36
@ref291:
	.byte $32,$85,$32,$85,$3b,$32,$85,$3b,$32,$83,$36,$3b,$3b,$3a,$83,$36
	.byte $3b,$3a,$81
	.byte $ff,$10
	.word @ref288
	.byte $ff,$12
	.word @ref289
@ref294:
	.byte $32,$85,$32,$85,$3b,$32,$85,$33,$33,$33,$32,$85,$3b,$32,$85,$3a
	.byte $81
@ref295:
	.byte $32,$85,$32,$85,$3b,$32,$85,$33,$3a,$93,$36,$37,$36,$81
@ref296:
	.byte $32,$8d,$36,$89,$32,$89,$32,$85,$37,$32,$89
@ref297:
	.byte $32,$85,$32,$85,$36,$89,$32,$89,$32,$85,$36,$85,$33,$32,$81
@ref298:
	.byte $32,$8d,$36,$89,$32,$89,$32,$85,$37,$32,$85,$36,$81
@ref299:
	.byte $32,$85,$32,$85,$36,$85,$37,$32,$89,$32,$85,$36,$85,$37,$36,$81
	.byte $ff,$0b
	.word @ref296
	.byte $ff,$0f
	.word @ref297
	.byte $ff,$0d
	.word @ref298
@ref303:
	.byte $32,$85,$32,$85,$37,$32,$85,$37,$32,$8b,$36,$3a,$85,$3a,$85
@ref304:
	.byte $32,$89,$33,$36,$89,$32,$89,$32,$85,$3b,$32,$89
@ref305:
	.byte $32,$89,$33,$36,$89,$32,$85,$37,$32,$85,$3a,$85,$33,$32,$81
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0f
	.word @ref305
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0f
	.word @ref305
	.byte $ff,$0c
	.word @ref304
@ref311:
	.byte $32,$89,$33,$36,$89,$32,$85,$37,$32,$83,$3a,$3a,$85,$3a,$85
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0f
	.word @ref305
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0f
	.word @ref305
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0f
	.word @ref305
	.byte $ff,$0c
	.word @ref304
@ref319:
	.byte $32,$89,$33,$36,$89,$32,$85,$37,$32,$85,$3a,$8d
	.byte $ff,$10
	.word @ref288
	.byte $ff,$12
	.word @ref289
	.byte $ff,$11
	.word @ref290
	.byte $ff,$13
	.word @ref291
	.byte $ff,$10
	.word @ref288
	.byte $ff,$12
	.word @ref289
	.byte $ff,$11
	.word @ref294
	.byte $ff,$0e
	.word @ref295
@ref328:
	.byte $32,$8d,$3c,$89,$40,$89,$40,$85,$3c,$89,$40,$81
@ref329:
	.byte $32,$85,$40,$85,$3d,$40,$85,$40,$89,$32,$85,$3d,$32,$89
	.byte $ff,$0c
	.word @ref328
@ref331:
	.byte $32,$85,$40,$85,$3d,$40,$85,$40,$85,$3d,$40,$85,$3c,$85,$3d,$3c
	.byte $81
	.byte $ff,$0c
	.word @ref328
	.byte $ff,$11
	.word @ref331
	.byte $ff,$0c
	.word @ref328
@ref335:
	.byte $32,$85,$40,$85,$3d,$40,$85,$32,$8f,$36,$37,$37,$37,$36,$81
@ref336:
	.byte $32,$89,$33,$37,$32,$85,$36,$89,$32,$85,$3b,$32,$85,$32,$81
@ref337:
	.byte $32,$89,$33,$37,$32,$85,$37,$32,$85,$32,$85,$3b,$33,$32,$85
	.byte $ff,$0f
	.word @ref336
@ref339:
	.byte $32,$89,$33,$37,$32,$85,$37,$32,$85,$32,$85,$3b,$33,$3b,$3a,$81
	.byte $ff,$0f
	.word @ref336
	.byte $ff,$0f
	.word @ref337
	.byte $ff,$0f
	.word @ref336
@ref343:
	.byte $32,$89,$33,$3b,$33,$3b,$3b,$3a,$8d,$36,$83,$36,$37,$36,$81
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0f
	.word @ref305
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0f
	.word @ref305
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0f
	.word @ref305
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0f
	.word @ref311
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0f
	.word @ref305
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0f
	.word @ref305
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0f
	.word @ref305
	.byte $ff,$0c
	.word @ref304
	.byte $ff,$0c
	.word @ref319
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$03
@ref360:
	.byte $a6,$32,$a8,$32,$a6,$38,$a8,$32,$a6,$3c,$a8,$32,$a6,$40,$a8,$38
	.byte $a6,$46,$a8,$3c,$a6,$40,$a8,$40,$a6,$3c,$a8,$46,$a6,$38,$a8,$40
	.byte $a6,$32,$a8,$3c,$a6,$38,$a8,$38,$a6,$3c,$a8,$32,$a6,$40,$a8,$38
	.byte $a6,$46,$a8,$3c,$a6,$40,$a8,$40,$a6,$3c,$a8,$46,$a6,$38,$a8,$40
@ref361:
	.byte $a6,$32,$a8,$3c,$a6,$38,$a8,$38,$a6,$3c,$a8,$32,$a6,$40,$a8,$38
	.byte $a6,$46,$a8,$3c,$a6,$40,$a8,$40,$a6,$3c,$a8,$46,$a6,$38,$a8,$40
	.byte $a6,$32,$a8,$3c,$a6,$38,$a8,$38,$a6,$3c,$a8,$32,$a6,$40,$a8,$38
	.byte $a6,$46,$a8,$3c,$a6,$40,$a8,$40,$a6,$3c,$a8,$46,$a6,$38,$a8,$40
@song1ch0loop:
	.byte $ff,$20
	.word @ref360
	.byte $ff,$20
	.word @ref361
	.byte $ff,$20
	.word @ref360
	.byte $ff,$20
	.word @ref361
	.byte $ff,$20
	.word @ref360
	.byte $ff,$20
	.word @ref361
	.byte $ff,$20
	.word @ref360
	.byte $ff,$20
	.word @ref361
	.byte $ff,$20
	.word @ref360
	.byte $ff,$20
	.word @ref361
	.byte $ff,$20
	.word @ref360
	.byte $ff,$20
	.word @ref361
	.byte $ff,$20
	.word @ref360
@ref375:
	.byte $a6,$32,$a8,$3c,$a6,$38,$a8,$38,$a6,$3c,$a8,$32,$a6,$40,$a8,$38
	.byte $b4,$46,$a8,$3c,$b4,$40,$a8,$40,$b4,$3c,$a8,$46,$b4,$38,$a8,$40
	.byte $b6,$32,$a8,$3c,$b6,$38,$a8,$38,$b6,$3c,$a8,$32,$b6,$40,$a8,$38
	.byte $46,$3c,$40,$40,$3c,$46,$38,$40
@ref376:
	.byte $97,$b8,$36,$38,$83,$36,$85,$32,$85,$2e,$85,$32,$85
@ref377:
	.byte $9f,$32,$85,$36,$85,$2e,$85,$32,$85
@ref378:
	.byte $97,$36,$38,$83,$36,$85,$32,$85,$2e,$85,$32,$85
@ref379:
	.byte $9f,$30,$32,$83,$36,$85,$38,$85,$3c,$85
@ref380:
	.byte $9f,$3c,$40,$8b,$46,$85,$40,$85
@ref381:
	.byte $bf
@ref382:
	.byte $9f,$3c,$40,$8b,$46,$85,$4a,$85
@ref383:
	.byte $bf
	.byte $ff,$0c
	.word @ref378
	.byte $ff,$09
	.word @ref377
	.byte $ff,$0c
	.word @ref378
	.byte $ff,$0a
	.word @ref379
	.byte $ff,$08
	.word @ref380
@ref389:
	.byte $bf
	.byte $ff,$08
	.word @ref382
@ref391:
	.byte $bf
@ref392:
	.byte $87,$bc,$3e,$40,$87,$01,$3c,$40,$83,$3c,$85,$38,$85,$32,$36,$83
	.byte $32,$85
@ref393:
	.byte $8f,$32,$85,$36,$85,$36,$38,$83,$36,$85,$32,$85,$3c,$85
@ref394:
	.byte $87,$3a,$3c,$87,$01,$3e,$40,$83,$3c,$85,$38,$85,$36,$85,$32,$85
@ref395:
	.byte $8f,$2e,$32,$83,$36,$85,$36,$38,$83,$36,$85,$38,$8d
@ref396:
	.byte $3a,$3c,$8b,$00,$85,$3a,$3c,$93,$40,$85,$3a,$3c,$83
@ref397:
	.byte $bf
@ref398:
	.byte $bf
@ref399:
	.byte $87,$a6,$3d,$a8,$3d,$a6,$3d,$a8,$3d,$a6,$40,$85,$a8,$3c,$85,$a6
	.byte $46,$85,$a8,$40,$85,$46,$85
	.byte $ff,$11
	.word @ref392
	.byte $ff,$0e
	.word @ref393
	.byte $ff,$10
	.word @ref394
	.byte $ff,$0d
	.word @ref395
@ref404:
	.byte $3a,$3c,$8b,$00,$85,$3a,$3c,$93,$40,$85,$46,$85
@ref405:
	.byte $83,$01,$46,$85,$4a,$89,$01,$4a,$85,$4e,$8d,$50,$85
@ref406:
	.byte $46,$4a,$bb
@ref407:
	.byte $bf
@ref408:
	.byte $b6,$32,$a8,$32,$b6,$38,$a8,$32,$b6,$3c,$a8,$32,$b6,$40,$a8,$38
	.byte $b6,$46,$a8,$3c,$b6,$40,$a8,$40,$b6,$3c,$a8,$46,$b6,$38,$a8,$40
	.byte $b6,$32,$a8,$3c,$b6,$38,$a8,$38,$b6,$3c,$a8,$32,$b6,$40,$a8,$38
	.byte $b6,$46,$a8,$3c,$b6,$40,$a8,$40,$b6,$3c,$a8,$46,$b6,$38,$a8,$40
@ref409:
	.byte $b4,$32,$a8,$3c,$b4,$38,$a8,$38,$b4,$3c,$a8,$32,$b4,$40,$a8,$38
	.byte $b4,$46,$a8,$3c,$b4,$40,$a8,$40,$b4,$3c,$a8,$46,$b4,$38,$a8,$40
	.byte $b4,$32,$a8,$3c,$b4,$38,$a8,$38,$b4,$3c,$a8,$32,$b4,$40,$a8,$38
	.byte $b4,$46,$a8,$3c,$b4,$40,$a8,$40,$b4,$3c,$a8,$46,$b4,$38,$a8,$40
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@ref410:
	.byte $aa,$03,$03,$03,$a8,$03,$03,$02,$a1,$aa,$03,$02,$81
@ref411:
	.byte $03,$03,$03,$a8,$03,$03,$02,$a9
@song1ch1loop:
	.byte $ff,$0a
	.word @ref410
	.byte $ff,$07
	.word @ref411
	.byte $ff,$0a
	.word @ref410
	.byte $ff,$07
	.word @ref411
	.byte $ff,$0a
	.word @ref410
	.byte $ff,$07
	.word @ref411
	.byte $ff,$0a
	.word @ref410
	.byte $ff,$07
	.word @ref411
	.byte $ff,$0a
	.word @ref410
	.byte $ff,$07
	.word @ref411
	.byte $ff,$0a
	.word @ref410
	.byte $ff,$07
	.word @ref411
	.byte $ff,$0a
	.word @ref410
	.byte $ff,$07
	.word @ref411
@ref426:
	.byte $aa,$0d,$0d,$0c,$85,$25,$21,$0d,$0d,$0d,$0d,$0d,$ba,$37,$aa,$25
	.byte $ba,$33,$aa,$25,$20,$81
@ref427:
	.byte $0d,$0d,$0d,$ba,$33,$aa,$25,$21,$0d,$0d,$0d,$0d,$0d,$ba,$33,$aa
	.byte $25,$ba,$37,$aa,$25,$20,$81
@ref428:
	.byte $0d,$0d,$0d,$ba,$33,$aa,$25,$21,$0d,$0d,$0d,$0d,$0d,$ba,$37,$aa
	.byte $25,$ba,$33,$aa,$25,$20,$81
	.byte $ff,$11
	.word @ref427
@ref430:
	.byte $03,$03,$03,$ba,$3d,$aa,$1b,$17,$03,$03,$03,$03,$03,$ba,$41,$aa
	.byte $1b,$ba,$41,$aa,$1b,$16,$81
@ref431:
	.byte $03,$03,$03,$ba,$41,$aa,$1b,$17,$03,$03,$03,$03,$03,$ba,$41,$aa
	.byte $1a,$85,$1b,$16,$81
@ref432:
	.byte $03,$03,$02,$85,$1b,$17,$03,$03,$03,$03,$03,$ba,$41,$aa,$1b,$ba
	.byte $41,$aa,$1b,$16,$81
@ref433:
	.byte $03,$03,$03,$ba,$4b,$aa,$1b,$17,$03,$03,$03,$03,$03,$ba,$4b,$aa
	.byte $1a,$85,$1b,$16,$81
@ref434:
	.byte $0d,$0d,$0c,$85,$25,$21,$0d,$0d,$0d,$0d,$0d,$ba,$37,$aa,$25,$ba
	.byte $33,$aa,$25,$20,$81
	.byte $ff,$11
	.word @ref427
	.byte $ff,$11
	.word @ref428
	.byte $ff,$11
	.word @ref427
	.byte $ff,$11
	.word @ref430
	.byte $ff,$11
	.word @ref431
	.byte $ff,$11
	.word @ref432
	.byte $ff,$11
	.word @ref433
@ref442:
	.byte $10,$85,$11,$11,$29,$c0,$41,$aa,$11,$29,$11,$c0,$41,$aa,$11,$11
	.byte $29,$c0,$39,$aa,$25,$10,$81
@ref443:
	.byte $11,$c0,$33,$aa,$11,$11,$29,$c0,$33,$aa,$11,$29,$11,$c0,$37,$aa
	.byte $11,$11,$29,$c0,$37,$aa,$25,$10,$81
@ref444:
	.byte $0d,$c0,$3d,$aa,$0d,$0d,$25,$c0,$3d,$aa,$0d,$25,$0d,$c0,$41,$aa
	.byte $0d,$0d,$25,$c0,$39,$aa,$21,$0c,$81
@ref445:
	.byte $0d,$c0,$33,$aa,$0d,$0d,$25,$c0,$33,$aa,$0d,$25,$0d,$c0,$37,$aa
	.byte $0d,$0d,$25,$c0,$37,$aa,$21,$0c,$81
@ref446:
	.byte $03,$c0,$39,$aa,$03,$03,$1b,$c0,$3d,$aa,$03,$1b,$03,$c0,$3d,$aa
	.byte $03,$03,$1b,$c0,$3d,$aa,$17,$02,$81
@ref447:
	.byte $03,$c0,$3d,$aa,$03,$03,$1b,$c0,$3d,$aa,$03,$1b,$03,$c0,$3d,$aa
	.byte $03,$03,$1a,$85,$17,$02,$81
@ref448:
	.byte $02,$85,$03,$03,$1a,$85,$03,$1b,$02,$85,$03,$03,$1a,$85,$17,$02
	.byte $81
@ref449:
	.byte $02,$85,$03,$03,$1a,$85,$03,$1b,$02,$85,$03,$03,$1a,$85,$1f,$02
	.byte $81
	.byte $ff,$11
	.word @ref442
	.byte $ff,$11
	.word @ref443
	.byte $ff,$11
	.word @ref444
	.byte $ff,$11
	.word @ref445
	.byte $ff,$11
	.word @ref446
@ref455:
	.byte $03,$c0,$47,$aa,$03,$03,$1b,$c0,$47,$aa,$03,$1b,$03,$c0,$4b,$aa
	.byte $03,$03,$1b,$c0,$4f,$aa,$17,$02,$81
@ref456:
	.byte $03,$c0,$51,$aa,$03,$03,$1b,$c0,$4b,$aa,$03,$1b,$03,$c0,$4b,$aa
	.byte $03,$03,$1b,$c0,$4b,$aa,$17,$02,$81
@ref457:
	.byte $02,$85,$03,$03,$1a,$85,$03,$1b,$02,$85,$a6,$02,$85,$b4,$02,$85
	.byte $b6,$02,$85
	.byte $ff,$0a
	.word @ref410
	.byte $ff,$07
	.word @ref411
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@ref460:
	.byte $bf
@ref461:
	.byte $bf
@song1ch2loop:
@ref462:
	.byte $bf
@ref463:
	.byte $bf
@ref464:
	.byte $bf
@ref465:
	.byte $bf
@ref466:
	.byte $bf
@ref467:
	.byte $bf
@ref468:
	.byte $b0,$33,$39,$3d,$41,$47,$41,$3d,$39,$33,$39,$3d,$41,$47,$41,$3d
	.byte $38,$81
@ref469:
	.byte $33,$39,$3d,$41,$47,$41,$3d,$39,$33,$39,$3d,$41,$47,$41,$3d,$38
	.byte $81
	.byte $ff,$11
	.word @ref469
	.byte $ff,$11
	.word @ref469
@ref472:
	.byte $b2,$33,$39,$3d,$41,$47,$41,$3d,$39,$33,$39,$3d,$41,$47,$41,$3d
	.byte $38,$81
	.byte $ff,$11
	.word @ref469
	.byte $ff,$11
	.word @ref469
@ref475:
	.byte $b0,$4b,$51,$55,$59,$5f,$59,$55,$51,$4b,$51,$55,$59,$5f,$59,$55
	.byte $50,$81
@ref476:
	.byte $aa,$24,$00,$24,$00,$24,$85,$3d,$39,$24,$00,$24,$00,$24,$00,$24
	.byte $00,$24,$85,$3d,$01,$3d,$38,$81
@ref477:
	.byte $24,$00,$24,$00,$24,$85,$3d,$39,$24,$00,$24,$00,$24,$00,$24,$00
	.byte $24,$85,$3d,$01,$3d,$38,$81
	.byte $ff,$17
	.word @ref477
	.byte $ff,$17
	.word @ref477
@ref480:
	.byte $1a,$00,$1a,$00,$1a,$85,$33,$2f,$1a,$00,$1a,$00,$1a,$00,$1a,$00
	.byte $1a,$85,$33,$01,$33,$2e,$81
@ref481:
	.byte $1a,$00,$1a,$00,$54,$59,$00,$59,$01,$1a,$00,$1a,$00,$58,$83,$00
	.byte $1a,$85,$54,$85,$50,$85
	.byte $ff,$17
	.word @ref480
@ref483:
	.byte $1a,$00,$1a,$00,$60,$63,$00,$63,$01,$1a,$00,$1a,$00,$62,$89,$01
	.byte $5e,$85,$58,$85
	.byte $ff,$17
	.word @ref477
	.byte $ff,$17
	.word @ref477
	.byte $ff,$17
	.word @ref477
	.byte $ff,$17
	.word @ref477
	.byte $ff,$17
	.word @ref480
	.byte $ff,$16
	.word @ref481
	.byte $ff,$17
	.word @ref480
	.byte $ff,$14
	.word @ref483
@ref492:
	.byte $29,$01,$28,$00,$28,$00,$40,$85,$28,$00,$41,$29,$01,$28,$00,$28
	.byte $00,$40,$85,$3d,$28,$00
	.byte $ff,$16
	.word @ref492
@ref494:
	.byte $25,$01,$24,$00,$24,$00,$3c,$85,$24,$00,$3d,$25,$01,$24,$00,$24
	.byte $00,$3c,$85,$38,$00,$24,$00
@ref495:
	.byte $25,$01,$24,$00,$24,$00,$3c,$85,$24,$00,$3d,$25,$01,$24,$00,$24
	.byte $00,$3c,$85,$39,$24,$00
@ref496:
	.byte $1b,$01,$1a,$00,$1a,$00,$32,$85,$1a,$00,$33,$1b,$01,$1a,$00,$1a
	.byte $00,$32,$85,$2f,$1a,$00
	.byte $ff,$16
	.word @ref496
@ref498:
	.byte $55,$01,$1a,$00,$55,$32,$85,$55,$33,$1b,$01,$55,$1a,$00,$55,$01
	.byte $59,$1a,$00
@ref499:
	.byte $1b,$01,$be,$3c,$83,$00,$3c,$83,$00,$40,$83,$00,$aa,$1b,$01,$be
	.byte $46,$83,$00,$aa,$32,$85,$37,$1a,$00
	.byte $ff,$16
	.word @ref492
	.byte $ff,$16
	.word @ref492
	.byte $ff,$17
	.word @ref494
	.byte $ff,$16
	.word @ref495
@ref504:
	.byte $bc,$1b,$01,$aa,$1a,$00,$1a,$00,$32,$85,$1a,$00,$33,$1b,$01,$1a
	.byte $00,$1a,$00,$32,$85,$2f,$1a,$00
	.byte $ff,$16
	.word @ref496
	.byte $ff,$13
	.word @ref498
@ref507:
	.byte $1b,$01,$be,$3c,$83,$00,$3c,$83,$00,$40,$83,$00,$aa,$1a,$85,$be
	.byte $4a,$8d,$33,$00,$81
@ref508:
	.byte $32,$95,$aa,$2c,$24,$22,$1a,$00,$9d
@ref509:
	.byte $bf
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@ref510:
	.byte $bf
@ref511:
	.byte $bf
@song1ch3loop:
@ref512:
	.byte $bf
@ref513:
	.byte $bf
@ref514:
	.byte $bf
@ref515:
	.byte $bf
@ref516:
	.byte $bf
@ref517:
	.byte $bf
@ref518:
	.byte $ac,$1f,$1f,$ae,$1f,$ac,$1f,$1f,$1f,$ae,$1f,$ac,$1f,$1f,$1f,$ae
	.byte $1f,$ac,$1f,$1f,$1f,$ae,$1f,$ac,$1e,$81
@ref519:
	.byte $1f,$1f,$ae,$1f,$ac,$1f,$1f,$1f,$ae,$1f,$ac,$1f,$1f,$1f,$ae,$1f
	.byte $ac,$1f,$1f,$1f,$ae,$1f,$ac,$1e,$81
	.byte $ff,$11
	.word @ref519
@ref521:
	.byte $1f,$1f,$ae,$1f,$ac,$1f,$1f,$1f,$ae,$1f,$ac,$1f,$1f,$1f,$ae,$1f
	.byte $ac,$1f,$ae,$1f,$ac,$1f,$ae,$1f,$1e,$81
	.byte $ff,$11
	.word @ref518
	.byte $ff,$11
	.word @ref519
@ref524:
	.byte $ae,$1d,$ac,$1f,$ae,$1f,$ac,$1f,$ae,$1d,$ac,$1f,$ae,$1f,$ac,$1f
	.byte $ae,$1d,$ac,$1f,$ae,$1f,$ac,$1f,$ae,$1d,$ac,$1f,$ae,$1f,$ac,$1e
	.byte $81
@ref525:
	.byte $ae,$18,$8d,$1a,$8d,$1c,$8d,$1e,$8d
@ref526:
	.byte $ac,$1f,$1f,$ae,$1e,$85,$ac,$1f,$1f,$ae,$1e,$85,$ac,$1f,$1f,$ae
	.byte $1e,$85,$ac,$1f,$1f,$ae,$1e,$85
	.byte $ff,$10
	.word @ref526
	.byte $ff,$10
	.word @ref526
	.byte $ff,$10
	.word @ref526
	.byte $ff,$10
	.word @ref526
	.byte $ff,$10
	.word @ref526
	.byte $ff,$10
	.word @ref526
@ref533:
	.byte $ac,$1f,$1f,$ae,$1e,$85,$ac,$1f,$1f,$ae,$1e,$85,$ac,$1f,$1f,$ae
	.byte $1e,$85,$1a,$85,$1b,$1c,$81
	.byte $ff,$10
	.word @ref526
	.byte $ff,$10
	.word @ref526
	.byte $ff,$10
	.word @ref526
	.byte $ff,$10
	.word @ref526
	.byte $ff,$10
	.word @ref526
	.byte $ff,$10
	.word @ref526
	.byte $ff,$10
	.word @ref526
	.byte $ff,$11
	.word @ref533
@ref542:
	.byte $ac,$1d,$1f,$1d,$1f,$ae,$1c,$85,$ac,$1d,$1f,$1d,$1f,$1d,$1f,$ae
	.byte $1c,$85,$1e,$85
	.byte $ff,$10
	.word @ref542
	.byte $ff,$10
	.word @ref542
	.byte $ff,$10
	.word @ref542
	.byte $ff,$10
	.word @ref542
@ref547:
	.byte $1d,$ac,$1f,$ae,$1e,$85,$1d,$ac,$1f,$ae,$1e,$85,$1d,$ac,$1f,$ae
	.byte $1e,$85,$1d,$ac,$1f,$ae,$1e,$85
	.byte $ff,$10
	.word @ref542
@ref549:
	.byte $1d,$ac,$1f,$ae,$1e,$85,$1d,$ac,$1f,$ae,$1e,$85,$1d,$ac,$1f,$ae
	.byte $1e,$85,$1a,$85,$1b,$1c,$81
	.byte $ff,$10
	.word @ref542
	.byte $ff,$10
	.word @ref542
	.byte $ff,$10
	.word @ref542
	.byte $ff,$10
	.word @ref542
	.byte $ff,$10
	.word @ref542
	.byte $ff,$10
	.word @ref547
	.byte $ff,$10
	.word @ref542
@ref557:
	.byte $1b,$ac,$1f,$ae,$1e,$85,$1b,$ac,$1f,$ae,$1e,$85,$1a,$85,$1e,$85
	.byte $1a,$85,$1e,$85
@ref558:
	.byte $18,$85,$1a,$85,$1c,$85,$1e,$a5
@ref559:
	.byte $bf
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@ref560:
	.byte $bf
@ref561:
	.byte $bf
@song1ch4loop:
@ref562:
	.byte $bf
@ref563:
	.byte $bf
@ref564:
	.byte $32,$8d,$32,$8d,$32,$8d,$32,$8d
@ref565:
	.byte $32,$8d,$32,$8d,$32,$8d,$32,$89,$32,$81
	.byte $ff,$08
	.word @ref564
@ref567:
	.byte $32,$8d,$32,$8d,$32,$85,$37,$33,$36,$85,$37,$36,$81
@ref568:
	.byte $32,$8d,$36,$8d,$32,$8d,$36,$8d
@ref569:
	.byte $32,$8d,$36,$8d,$32,$8d,$36,$85,$32,$85
	.byte $ff,$08
	.word @ref568
@ref571:
	.byte $32,$8d,$36,$8d,$32,$8d,$36,$85,$37,$36,$81
	.byte $ff,$08
	.word @ref568
	.byte $ff,$0a
	.word @ref569
@ref574:
	.byte $32,$8d,$36,$8d,$32,$8d,$36,$89,$36,$36
@ref575:
	.byte $36,$8d,$32,$8d,$32,$8d,$37,$37,$37,$36,$81
	.byte $ff,$08
	.word @ref568
	.byte $ff,$08
	.word @ref568
	.byte $ff,$08
	.word @ref568
	.byte $ff,$0b
	.word @ref571
	.byte $ff,$08
	.word @ref568
	.byte $ff,$08
	.word @ref568
	.byte $ff,$08
	.word @ref568
@ref583:
	.byte $32,$8d,$36,$89,$37,$32,$85,$36,$85,$36,$85,$37,$36,$81
	.byte $ff,$08
	.word @ref568
	.byte $ff,$08
	.word @ref568
	.byte $ff,$08
	.word @ref568
	.byte $ff,$0b
	.word @ref571
	.byte $ff,$08
	.word @ref568
	.byte $ff,$08
	.word @ref568
	.byte $ff,$08
	.word @ref568
	.byte $ff,$0e
	.word @ref583
@ref592:
	.byte $32,$89,$33,$36,$85,$33,$33,$33,$32,$85,$33,$36,$85,$32,$85
	.byte $ff,$0f
	.word @ref592
	.byte $ff,$0f
	.word @ref592
@ref595:
	.byte $32,$89,$33,$36,$85,$33,$37,$33,$32,$85,$33,$36,$36,$83,$37,$36
	.byte $81
	.byte $ff,$0f
	.word @ref592
@ref597:
	.byte $32,$89,$33,$36,$85,$33,$37,$33,$32,$85,$33,$36,$85,$37,$36,$81
	.byte $ff,$0f
	.word @ref592
@ref599:
	.byte $33,$33,$32,$85,$36,$85,$33,$36,$36,$33,$32,$85,$33,$36,$36,$83
	.byte $37,$36,$81
	.byte $ff,$0f
	.word @ref592
	.byte $ff,$0f
	.word @ref592
	.byte $ff,$0f
	.word @ref592
	.byte $ff,$11
	.word @ref595
	.byte $ff,$0f
	.word @ref592
	.byte $ff,$10
	.word @ref597
	.byte $ff,$0f
	.word @ref592
@ref607:
	.byte $37,$37,$37,$37,$36,$85,$37,$33,$37,$37,$37,$37,$36,$85,$36,$85
@ref608:
	.byte $32,$bd
@ref609:
	.byte $bf
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$08
@song2ch0loop:
@ref610:
	.byte $be,$29,$82,$31,$31,$33,$33,$33,$37,$36,$36,$36,$34,$9b
@ref611:
	.byte $bf
@ref612:
	.byte $a6,$32,$bd
@ref613:
	.byte $bf
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref614:
	.byte $bf
@ref615:
	.byte $bf
@ref616:
	.byte $bf
@ref617:
	.byte $bf
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref618:
	.byte $bf
@ref619:
	.byte $bf
	.byte $ff,$11
	.word @ref468
	.byte $ff,$11
	.word @ref469
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref622:
	.byte $bf
@ref623:
	.byte $bf
	.byte $ff,$11
	.word @ref518
	.byte $ff,$11
	.word @ref519
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref626:
	.byte $bf
@ref627:
	.byte $bf
	.byte $ff,$08
	.word @ref564
	.byte $ff,$0a
	.word @ref565
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$0a
@song3ch0loop:
@ref630:
	.byte $f9,$85
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref631:
	.byte $f9,$85
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref632:
	.byte $f9,$85
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref633:
	.byte $92,$1e,$8b,$9a,$0e,$97,$1a,$8f,$92,$1e,$95,$9a,$0e,$97,$1a,$91
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref634:
	.byte $f9,$85
	.byte $fd
	.word @song3ch4loop
